version: "3"

networks:
  laravel:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  nginx:
    image: nginx:1.19.0-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
