version: "3.7"

networks:
  laravel:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pusatphp
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: pusatmysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "sbs"
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - laravel
  nginx:
    image: nginx:latest
    container_name: pusatnginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
